name: Deploy Sample Compose Web App to Netlify

on:
  release:
    types:
      [ published ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Web app
        run: ./gradlew wasmJsBrowserDistribution

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v2
        with:
          publish-dir: ./sample/web-wasm/build/dist/wasmJs/productionExecutable
          #updating the production branch for testing if Netlify automatically deploys the web app
          production-branch: feat/netlify-release-deploy
          github-token: ${{ secrets.GITHUB_TOKEN }}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}